@baseUrl = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4NDYwOTM2NCwianRpIjoiZWE1MzdjNmYtOTNjNi00MjI3LWIwNzUtMTg2NGQ2NmIzMTk5IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIwMjM1MjE4IiwibmJmIjoxNzg0NjA5MzY0LCJjc3JmIjoiNGNlN2QyOGItZDUyMy00ZTJjLThmMmYtNmRmMjI5YzYxYzdlIiwiZXhwIjoxNzg0NjI3MzY0LCJ1c2VyX2lkIjoxfQ.ku1A--krhXDYZcsNIW2ZABLpbx5j2SbvJDie2n2M_DI

### ==========================================
### 1. SIGN-IN - Iniciar sesión
### ==========================================
POST {{baseUrl}}/api/sign-in
Content-Type: application/json

{
  "code": "20235218",
  "password": "ulima123"
}

### ==========================================
### 2. DELEGADO - Listar Secciones
### ==========================================
GET {{baseUrl}}/api/v1/delegate/sections
Authorization: Bearer {{token}}

### ==========================================
### 3. DELEGADO - Publicar Anuncio en una Sección
### ==========================================
POST {{baseUrl}}/api/v1/delegate/announcements
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "section_id": 1,
  "title": "Prueba de Anuncio 2",
  "message": "Estimados, recuerden que la entrega del Trabajo Final es este domingo a las 11:59 PM sin prórroga."
}

### ==========================================
### 4. ANUNCIOS - Listar Anuncios de una Sección
### ==========================================
GET {{baseUrl}}/api/v1/sections/1/announcements
Authorization: Bearer {{token}}

### ==========================================
### 5. ESTADÍSTICAS - Obtener estadísticas dinámicas de una Sección
### ==========================================
GET {{baseUrl}}/api/v1/sections/1/statistics
Authorization: Bearer {{token}}

