@baseUrl = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4MzA0OTU3MiwianRpIjoiNWFiMTBkZWEtMzdlMy00YmEzLThkY2YtYThiYWQwZGYzODcwIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIwMjMyNTQ4IiwibmJmIjoxNzgzMDQ5NTcyLCJjc3JmIjoiMzA4ZGIxMmMtNTUwZi00NzQ4LTllNTUtMjYxMDFlODYzODQzIiwiZXhwIjoxNzgzMDY3NTcyLCJ1c2VyX2lkIjoyfQ.txa8b3CVxiYWQDF8tJcdx2nXROGjWCAJObtXZZAT9JY
### ==========================================
### 1. SIGN-IN - Iniciar sesión
### ==========================================
POST {{baseUrl}}/api/sign-in
Content-Type: application/json

{
  "code": "20232548",
  "password": "ulima123"
}

### ==========================================
### 2. SIGN-OUT - Cerrar sesión
### ==========================================
GET {{baseUrl}}/api/sign-out
Authorization: Bearer {{token}}

### ==========================================
### 3. PERFIL - Obtener datos del usuario autenticado
### ==========================================
GET {{baseUrl}}/api/me
Authorization: Bearer {{token}}