@baseUrl = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4NDUxNjMyNiwianRpIjoiNjkxNzYxZTMtOGMzNS00OGIzLThiMjYtOWU1ZmM4ZmJiYzZjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIwMjMyNTQ4IiwibmJmIjoxNzg0NTE2MzI2LCJjc3JmIjoiMTA3OTliNjAtNGRlOC00MDRhLTgwM2YtMjY1Nzc2NzU3ZTNiIiwiZXhwIjoxNzg0NTM0MzI2LCJ1c2VyX2lkIjoyfQ.9te69DejoU9Zwa7x8x1HIVYmapVWiXNp4L00by3jJl0
### ==========================================
### 1. SIGN-IN - Iniciar sesión
### ==========================================
POST {{baseUrl}}/api/sign-in
Content-Type: application/json

{
  "code": "20232548",
  "password": "ulima123"
}

### ==========================================
### 2. SIGN-OUT - Cerrar sesión
### ==========================================
GET {{baseUrl}}/api/sign-out
Authorization: Bearer {{token}}

### ==========================================
### 3. PERFIL - Obtener datos del usuario autenticado
### ==========================================
GET {{baseUrl}}/api/me
Authorization: Bearer {{token}}